version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: GameVaultDB
    environment:
      POSTGRES_USER: GAMEVAULT
      POSTGRES_PASSWORD: GAMEVAULT
      POSTGRES_DB: GAMEVAULT
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  gamevault:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/GAMEVAULT
      QUARKUS_DATASOURCE_USERNAME: GAMEVAULT
      QUARKUS_DATASOURCE_PASSWORD: GAMEVAULT
    depends_on:
      - postgres

volumes:
  pg_data:

