version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: GameVaultDB
    environment:
      POSTGRES_USER: GAMEVAULT
      POSTGRES_PASSWORD: GAMEVAULT
      POSTGRES_DB: GAMEVAULT
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "GAMEVAULT"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  quarkus:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: GameVaultAPI
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://GameVaultDB:5432/GAMEVAULT
      - QUARKUS_DATASOURCE_JDBC_USERNAME=GAMEVAULT
      - QUARKUS_DATASOURCE_JDBC_PASSWORD=GAMEVAULT

volumes:
  pg_data:
