version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: GameVaultDB
    environment:
      POSTGRES_USER: GAMEVAULT
      POSTGRES_PASSWORD: GAMEVAULT
      POSTGRES_DB: GAMEVAULT
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
