INSERT INTO genre (id, "name") VALUES
(1, 'Action'),
(2, 'Adventure'),
(3, 'Beat ''em Up'),
(4, 'Board Game'),
(5, 'Casino'),
(6, 'Compilation'),
(7, 'Construction and Management Simulation'),
(8, 'Education'),
(9, 'Fighting'),
(10, 'Flight Simulator'),
(11, 'Horror'),
(12, 'Life Simulation'),
(13, 'MMO'),
(14, 'Music'),
(15, 'Party'),
(16, 'Pinball'),
(17, 'Platform'),
(18, 'Puzzle'),
(19, 'Quiz'),
(20, 'Racing'),
(21, 'Role-Playing'),
(22, 'Sandbox'),
(23, 'Shooter'),
(24, 'Sports'),
(25, 'Stealth'),
(26, 'Strategy'),
(27, 'Vehicle Simulation'),
(28, 'Visual Novel'),
(29, 'RPG'),
(30, 'Strategy'),
(31, 'Simulation');