-- Create the PLAYER table
CREATE TABLE PLAYER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

-- Create the PLATFORM table
CREATE TABLE PLATFORM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Create the GENRE table
CREATE TABLE GENRE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Create the DEVELOPER table
CREATE TABLE DEVELOPER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- Create the VIDEOGAME table
CREATE TABLE VIDEOGAME (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    RELEASE_YEAR INT,
    PLATFORM_ID INT,
    GENRE_ID INT,
    DEVELOPER_ID INT,
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (DEVELOPER_ID) REFERENCES DEVELOPER(ID)
);

-- Create the PLAYER_VIDEOGAME table (tabla intermedia)
CREATE TABLE PLAYER_VIDEOGAME (
    ID SERIAL PRIMARY KEY,
    PLAYER_ID INT NOT NULL,
    VIDEOGAME_ID INT NOT NULL,
    DIGITAL BOOLEAN NOT NULL,
    PHYSICAL_STATUS VARCHAR(50),
    PURCHASE_DATE DATE,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER(ID),
    FOREIGN KEY (VIDEOGAME_ID) REFERENCES VIDEOGAME(ID)
);
