-- CREATE THE PLAYER TABLE
CREATE TABLE PLAYER (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

-- CREATE THE PLATFORM TABLE
CREATE TABLE PLATFORM (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- CREATE THE GENRE TABLE
CREATE TABLE GENRE (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- CREATE THE DEVELOPER TABLE
CREATE TABLE DEVELOPER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- CREATE THE VIDEOGAME TABLE
CREATE TABLE VIDEOGAME (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    RELEASE_YEAR INT,
    PLATFORM_ID INT,
    GENRE_ID INT,
    DEVELOPER_ID INT,
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID),
    FOREIGN KEY (DEVELOPER_ID) REFERENCES DEVELOPER(ID)
);

-- CREATE GAMECOLLECTION
CREATE TABLE GAMECOLLECTION (
	ID BIGSERIAL NOT NULL,
	CREATEDDATE TIMESTAMP(6) NULL,
	DESCRIPTION VARCHAR(255) NULL,
	FAVORITE BOOL NOT NULL,
	"NAME" VARCHAR(255) NULL,
	PLAYER_ID INT8 NULL
);

-- CREATE COLLECTION_VIDEOGAME
CREATE TABLE COLLECTION_VIDEOGAME (i	
	ID BIGSERIAL NOT NULL,
	COMPLETED BOOL NOT NULL,
	DATE_ADDED TIMESTAMP(6) NULL,
	DIGITAL BOOL NOT NULL,
	HOURSPLAYED INT4 NOT NULL,
	NOTES VARCHAR(255) NULL,
	PHYSICAL_STATUS VARCHAR(255) NULL,
	PURCHASE_DATE TIMESTAMP(6) NULL,
	RATING INT4 NOT NULL,
	STATUS VARCHAR(255) NULL,
	TIMES_COMPLETED INT4 NULL,
	COLLECTION_ID INT8 NULL,
	VIDEOGAME_ID INT8 NULL
);
