name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose -f docker-compose.dev.yml up -d

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin' 

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 30  # Ajusta el tiempo según sea necesario

      - name: Run Quarkus in dev mode
        run: ./mvnw compile quarkus:dev
        env:
          QUARKUS_HTTP_PORT: 8080

